 'use client'
import {useState} from 'react'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import { researchHref, type ResearchContext } from '@/lib/research-context'
export function CoachPicker({options,initial=[],context={}}:{options:{id:string;name:string|null}[];initial?:string[];context?:ResearchContext}){
 const duplicateNames=new Set(options.filter((c,i)=>options.some((other,j)=>i!==j && (other.name||'').trim().toLowerCase()===(c.name||'').trim().toLowerCase())).map(c=>c.name))
 const [query,setQuery]=useState(''),[selected,setSelected]=useState(initial);const router=useRouter()
 return <section className="rounded-lg border bg-card p-4"><h2 className="font-semibold">Choose coaches to compare</h2><p className="mt-1 text-sm text-muted-foreground">Select two to four. Compare conditions for success, evidence gaps and appointment feasibility before deciding who advances.</p><label className="mt-3 block text-sm">Find a coach<input className="mt-1 block w-full rounded border bg-background p-2" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search names"/></label><div className="mt-3 grid max-h-56 gap-2 overflow-y-auto sm:grid-cols-2">{options.filter(c=>(c.name||'').toLowerCase().includes(query.toLowerCase())||selected.includes(c.id)).map(c=><label className="flex gap-2 rounded border p-2 text-sm" key={c.id}><input type="checkbox" checked={selected.includes(c.id)} disabled={!selected.includes(c.id)&&selected.length>=4} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/><span>{c.name||'Unnamed coach'}{duplicateNames.has(c.name)&&<small className="block text-muted-foreground">Identity review needed · Record {c.id.slice(0,8)}</small>}</span></label>)}</div><p className="mt-3 text-xs text-muted-foreground">Repeated names are separate records until identity is confirmed. <Link className="underline" href="/coaches/identity-review">Review possible duplicates</Link></p><button className="mt-3 rounded bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50" disabled={selected.length<2} onClick={()=>router.push(researchHref(`/coaches/compare?ids=${selected.join(',')}`, context))}>Compare {selected.length} selected</button></section>
}
