import type { DeepResearchProfile, DeepResearchSection } from './deep-research-types.ts'

// Editorial research, not API observations or scoring inputs. Sources opened 2026-09-14.
// Every period is historical; reviewedAt does not certify present employment.
type Source = DeepResearchProfile['sources'][number]
const source = (url: string, title: string, publisher: string): Source => ({ url, title, publisher })
const s = {
  crosby: source('https://www.port-vale.co.uk/news/2023/may/port-vale-fc-appoint-andy-crosby-as-manager', 'Port Vale FC Appoint Andy Crosby as Manager', 'Port Vale'),
  crosbyInterview: source('https://www.port-vale.co.uk/news/2023/may/first-interview--port-vale-manager-andy-crosby', 'First Interview | Port Vale Manager Andy Crosby', 'Port Vale'),
  ramsey: source('https://www.cardiffcityfc.co.uk/news/club-statement-ramsey-take-final-games', 'Club Statement | Ramsey to take final games', 'Cardiff City'),
  ramseyInterview: source('https://www.cardiffcityfc.co.uk/news/ramsey-pre-oxford-united-well-give-you-everything', 'Ramsey pre-Oxford United | We’ll give you everything', 'Cardiff City'),
  sheehan: source('https://www.swanseacity.com/news/alan-sheehan-i-am-honoured-have-opportunity', 'Alan Sheehan | I am honoured to have this opportunity', 'Swansea City'),
  sheehanApproach: source('https://www.swanseacity.com/news/alan-sheehan-wants-swansea-city-build-confidence-and-character', 'Alan Sheehan wants Swansea City to build confidence and character', 'Swansea City'),
  taylor: source('https://www.bwfc.co.uk/news/academy-coaches-take-interim-charge', 'Academy coaches take interim charge', 'Bolton Wanderers'),
  taylorYouth: source('https://www.bwfc.co.uk/news/sonny-back-b-team-returns', 'Sonny back as B Team returns', 'Bolton Wanderers'),
  whing: source('https://learning.coachesvoice.com/cv/andy-whing/', 'Overcoming adversity', 'Coaches’ Voice'),
  whingBarrow: source('https://www.skysports.com/football/news/11750/13400211/inside-barrow-andy-whing-and-iain-wood-on-why-the-underdog-spirit-suits-them-fine-as-they-try-to-beat-the-odds-again', 'Inside Barrow: Andy Whing and Iain Wood on why the underdog spirit suits them fine', 'Sky Sports'),
  woodman: source('https://www.skysports.com/football/news/37737/13493841/andy-woodman-exclusive-interview-league-two-leaders-bromley-are-the-real-set-piece-kings-forget-arsenal-and-brentford', 'Andy Woodman exclusive interview: League Two leaders Bromley are the real set-piece kings', 'Sky Sports'),
  dawson: source('https://www.lcfc.com/media-article/dawson-deliver-a-performance-for-the-fans', 'Dawson: Deliver a performance for the fans', 'Leicester City'),
  dawsonMatch: source('https://www.lcfc.com/media-article/dawson-we-needed-to-be-stronger', 'Dawson: We needed to be stronger', 'Leicester City'),
  gladwin: source('https://www.mkdons.com/news/2025/march/08/report--mk-dons-morecambe/', 'Report: MK Dons 2-1 Morecambe', 'MK Dons'),
  gladwinSanders: source('https://www.theleaguepaper.com/latest-news/football-league-division-one/mk-dons/437446/gladwin-hails-sanders-after-defender-gives-dons-victory/', 'Cheltenham Town 0-1 MK Dons: Ben Gladwin hails Jack Sanders as he guides Dons to victory', 'The League Paper'),
  adam: source('https://www.burnleyfootballclub.com/media-article/charlie-adam-on-player-development-u21s-progression-international-call-ups-and-more', 'Charlie Adam on player development, U21s season, international call-ups, and more', 'Burnley FC'),
  adamSetPlays: source('https://www.olbg.com/blogs/charlie-adam', 'Charlie Adam Exclusive Interview with OLBG', 'OLBG — direct interview'),
  brunt: source('https://www.wba.co.uk/news/chris-brunt-honour-help-were-disappointed-result', 'Chris Brunt: An honour to help, but we’re disappointed with result', 'West Bromwich Albion'),
  bruntResponse: source('https://www.wba.co.uk/news/chris-brunt-players-showed-heart-couldve-won-it', 'Chris Brunt: Players showed heart and could’ve won it', 'West Bromwich Albion'),
  hourihane: source('https://learning.coachesvoice.com/cv/conor-hourihane-barnsley/', 'From playing to coaching', 'Coaches’ Voice'),
  hourihaneHead: source('https://www.skysports.com/football/news/11095/13407835/conor-hourihane-interview-barnsley-boss-on-how-coaching-while-playing-led-him-to-a-head-coach-role-at-34', 'Conor Hourihane interview: Barnsley boss on how coaching while playing led him to a head coach role at 34', 'Sky Sports'),
  daniels: source('https://www.skysports.com/football/news/11095/13432084/charlie-daniels-interview-bournemouth-favourite-on-how-newcastles-eddie-howe-opened-his-eyes-to-coaching', 'Charlie Daniels interview: Bournemouth favourite on how Newcastle’s Eddie Howe opened his eyes to coaching', 'Sky Sports'),
  fuchs: source('https://www.newport-county.co.uk/news/former-leicester-city-premier-league-title-winner-christian-fuchs-newport-countys-new-manager', 'Former Leicester City Premier League title winner Christian Fuchs is Newport County’s new manager', 'Newport County'),
  fuchsPlayer: source('https://www.newport-county.co.uk/news/james-crole-newport-county-forward-ready-fire-crawley-town-clash', 'James Crole: Newport County forward ready to fire for Crawley Town clash', 'Newport County'),
  calderwood: source('https://www.ntfc.co.uk/news/2026/march/26/chairman-kelvin-thomas-on-the-search-for-a-new-manager/', 'Chairman Kelvin Thomas on the process to appoint a new manager', 'Northampton Town'),
  calderwoodYouth: source('https://www.ntfc.co.uk/news/2026/may/01/colin-calderwood-1-may/', 'Colin Calderwood on the team selection for Saturday and the next few weeks', 'Northampton Town'),
  kazim: source('https://www.crawleytownfc.com/news/2026/march/24/colin-kazim-richards-joins-as-head-coach/', 'Colin Kazim-Richards joins as Head Coach', 'Crawley Town'),
  kazimPermanent: source('https://www.crawleytownfc.com/news/2026/may/12/colin-kazim-richards-named-as-head-coach/', 'Colin Kazim-Richards named as Head Coach', 'Crawley Town'),
  horseman: source('https://www.bristolrovers.co.uk/news/david-horseman-were-probably-quite-unpredictable', 'David Horseman: We’re probably quite unpredictable', 'Bristol Rovers'),
  horsemanCup: source('https://www.bristolrovers.co.uk/news/david-horseman-i-hope-we-did-manager-proud-fa-cup-progression', 'David Horseman: I hope we did the manager proud in FA Cup progression', 'Bristol Rovers'),
  hughes: source('https://www.newport-county.co.uk/news/david-hughes-appointed-newport-county-manager', 'David Hughes appointed Newport County manager', 'Newport County'),
  hughesInterview: source('https://www.newport-county.co.uk/news/david-hughes-challenge-something-i-welcome', 'David Hughes: The challenge is something I welcome', 'Newport County'),
  livermore: source('https://southwarknews.co.uk/sport/football/millwall/david-livermore-on-whether-he-wants-the-millwall-job/', 'David Livermore on whether he wants the Millwall job', 'Southwark News — direct interview'),
  livermoreMatch: source('https://southwarknews.co.uk/sport/football/millwall/it-was-important-that-we-came-away-with-something-millwall-temporary-boss-on-0-0-draw-with-coventry-city/', 'It was important that we came away with something: Millwall temporary boss on 0-0 draw with Coventry City', 'Southwark News — direct interview'),
}
const titles: Record<DeepResearchSection['key'], string> = {
  career: 'Career context', 'in-possession': 'In possession', 'out-of-possession': 'Out of possession',
  adaptability: 'Adaptability', development: 'Player development', management: 'Player management',
}
function section(key: DeepResearchSection['key'], period: string, text: string, ...sources: Source[]): DeepResearchSection {
  return { key, title: titles[key], points: [{ text, period, sourceUrls: sources.map(item => item.url) }] }
}
function profile(apiId: number, name: string, sections: DeepResearchSection[], limitations: string[]): DeepResearchProfile {
  const urls = new Set(sections.flatMap(item => item.points.flatMap(point => point.sourceUrls)))
  return { apiId, name, reviewedAt: '2026-09-14', sections, sources: Object.values(s).filter(item => urls.has(item.url)), limitations }
}

export const DEEP_DIRECTORY_BRITAIN_PROFILES: DeepResearchProfile[] = [
  profile(12497, 'Andrew Crosby', [
    section('career', 'Port Vale, 2021–May 2023', 'Crosby’s permanent appointment followed assistant and acting-manager responsibilities at Vale. The club credited his contribution during the 2022 promotion campaign. His earlier work alongside Nigel Adkins included Southampton’s successive promotions; those were staff achievements, not evidence that Crosby independently led those teams.', s.crosby),
    section('adaptability', 'Port Vale appointment, May 2023', 'Vale chose an internal appointment with existing knowledge of the squad and organisation. In his first interview Crosby emphasised understanding the owners’ values and the people around the club. This supports a continuity-based transition from assistant to manager, rather than evidence of a wholesale tactical rebuild.', s.crosbyInterview),
    section('management', 'Port Vale first interview, May 2023', 'His stated baseline was sustained daily effort and responsibility towards supporters. The emphasis was on conduct throughout the working week, not simply matchday motivation. These are explicit expectations he communicated on appointment; the interview does not independently demonstrate how consistently players met them.', s.crosbyInterview),
  ], ['Published as Andy Crosby in club sources; retained assigned Andrew Crosby identity 12497. These appointment interviews do not establish detailed pressing or build-up mechanisms, or September 2026 employment.']),
  profile(24995, 'Aaron Ramsey', [
    section('career', 'Cardiff City, April 2025', 'Cardiff assigned Ramsey the final three league games after Omer Riza’s departure. The announced support group included Chris Gunter and Joe Ralls alongside other coaches. The important scope is a short caretaker intervention, not a completed permanent managerial project.', s.ramsey),
    section('adaptability', 'Cardiff preparation for Oxford United, April 2025', 'Ramsey described immediate meetings to prepare players mentally and recognised Oxford’s organisation and improved form. He wanted more energy, intensity and proactive play. Those were priorities expressed before a match, not measured evidence of a high press or a settled possession structure.', s.ramseyInterview),
    section('management', 'Cardiff preparation for Oxford United, April 2025', 'He used the staff’s and players’ links to Cardiff to reinforce responsibility to the club. His appeal combined collective effort with a request for supporters’ backing in a difficult situation. The evidence concerns building short-term togetherness rather than recruitment, a development pathway or sustained dressing-room outcomes.', s.ramseyInterview),
  ], ['This is the Welsh international Aaron James Ramsey, not the younger English player. Three-game caretaker scope cannot support a mature tactical classification; current role is not verified here.']),
  profile(21599, 'Alan Sheehan', [
    section('career', 'Swansea City, February–April 2025', 'Sheehan’s second caretaker spell led to permanent appointment after seven wins and seven clean sheets in twelve games. Swansea also recorded his earlier temporary spell in 2023/24. The stronger spring results provide a defined sample, although they do not isolate his contribution from personnel or opponent effects.', s.sheehan),
    section('out-of-possession', 'Swansea City, spring 2025', 'The club’s appointment account identified more aggressive pressing and transition attacks. Sheehan argued that possession alone does not mean control when opponents are waiting to counter. His objective was to manage games both with and without the ball, rather than judge performance by passing volume.', s.sheehan),
    section('adaptability', 'Swansea City interview, March 2025', 'He wanted players able to change the speed of a game and attack with either a short or extended passing sequence according to the opening. Energy, resilience and using the available players effectively accompanied that flexibility. This is a specific explanation of intent, not a universal formation prescription.', s.sheehanApproach),
  ], ['The spring 2025 sample does not certify later employment or prove that the same pressing intensity transfers to every squad. No tracking data or causal player-development assessment accompanies these interviews.']),
  profile(18594, 'Andy Taylor', [
    section('career', 'Bolton Wanderers, January 2025', 'Bolton placed Taylor in an interim coaching group led by Julian Darby, alongside Andrew Tutte. The announcement identified Taylor’s B-team work from January 2024 and previous assistant experience at AFC Fylde. It does not identify him as sole interim manager of Bolton’s first team.', s.taylor),
    section('development', 'Bolton B team, January 2025', 'The B-team return against Liverpool U21 supplied a competitive test for younger players against stronger academy opposition. Sonny Sharples-Ahmed completed the match after involvement on the senior bench. This illustrates the practical link between development fixtures and first-team exposure within Taylor’s coaching remit.', s.taylorYouth),
    section('management', 'Bolton B team, January 2025', 'The same fixture gave Conor Carty seventy minutes after a lengthy absence. Combining a returning senior prospect with younger teammates made the game useful beyond its narrow defeat. This is evidence of managed playing opportunities in a development setting, not proof Taylor alone designed the rehabilitation programme.', s.taylorYouth),
  ], ['Matched to the former AFC Fylde assistant and Bolton B-team coach. Provider senior-role rows must not convert the Darby-led coaching trio into sole Taylor managerial credit. Detailed first-team tactics remain unverified.']),
  profile(13139, 'Andy Whing', [
    section('career', 'Banbury United, 2020–2022; retrospective May 2026', 'Whing described building Banbury around ambitious younger players and a division of labour in which recruitment support continued while he coached. The 2021/22 title brought 102 points. His account links the achievement to a deliberately assembled group and practical support, including affordable nutrition arrangements.', s.whing),
    section('adaptability', 'Barrow, January–August 2025', 'At Barrow the immediate priority was restoring basic defensive work and making the side harder to beat. His August interview describes adaptability within limited resources rather than insisting on one ambitious model. The context matters: stabilising a struggling League Two side was different from his Banbury construction project.', s.whingBarrow),
    section('management', 'Solihull Moors, 2024; retrospective May 2026', 'Before Wembley, training dimensions were adjusted to familiarise players with the larger stage. After two final defeats, he emphasised maintaining a positive working environment. This supplies concrete preparation and emotional-management examples, while the defeats caution against treating preparation quality as a guarantee of success.', s.whing),
  ], ['Retrospective self-report is attributed to Whing, not independently measured causation. Barrow’s later difficulties limit extrapolation from the initial improvement. No current appointment is asserted.']),
  profile(14319, 'Andy Woodman', [
    section('career', 'Bromley, January 2026 interview', 'Woodman’s account describes Bromley leading League Two while working with comparatively constrained resources. He presented repeatable set-piece opportunities as an area where detailed preparation could offset those constraints. This is a period-specific account of his EFL coaching work, not a claim that league position alone proves tactical superiority.', s.woodman),
    section('in-possession', 'Bromley, 2024/25–January 2026', 'Bromley sought to reach dangerous areas quickly rather than accumulate unnecessary passes. Set plays were a substantial scoring route, with Michael Cheek a prominent beneficiary. The emphasis was on creating deliverable situations for the available attackers; the evidence does not imply the team never combined through open play.', s.woodman),
    section('management', 'Bromley, January 2026 interview', 'Preparation included classroom work and a playbook assigning players clear responsibilities at restarts. That makes the approach teachable and repeatable rather than merely dependent on aggression or height. Woodman’s explanation supports organised rehearsal, although the interview cannot separate coaching effects from delivery quality and individual finishing.', s.woodman),
  ], ['This profile relies on one substantive direct interview. It does not establish detailed open-play defensive triggers, individual development outcomes or employment as of September 2026.']),
  profile(9443, 'Ben Dawson', [
    section('career', 'Leicester City, November 2024', 'Dawson temporarily coordinated the first team alongside Danny Alcock and Andy Hughes before Ruud van Nistelrooy took over. His pre-match comments stressed preparation and a performance for supporters. The assignment was transitional first-team cover, not evidence of a permanent Leicester managerial appointment.', s.dawson),
    section('adaptability', 'Leicester at Brentford, 30 November 2024', 'The temporary staff selected three centre-backs as an opponent-specific decision; an early injury to Caleb Okoli then disrupted the plan. Dawson explained the reasoning after the match. This is a documented tactical adjustment within a shared staff remit, not proof that a back three defines his coaching identity.', s.dawsonMatch),
    section('out-of-possession', 'Leicester at Brentford, 30 November 2024', 'After conceding four despite scoring first, Dawson said Leicester needed greater strength in defensive situations and better decisions to restrict chances. Attacking positives did not erase that assessment. The result is important counter-evidence against describing the temporary tactical change as an established defensive improvement.', s.dawsonMatch),
  ], ['One match under temporary shared leadership is insufficient for a stable playing-style classification. No academy-development outcomes or current-role claim are inferred from this senior cover.']),
  profile(23621, 'Ben Gladwin', [
    section('career', 'MK Dons, March 2025', 'The club’s Morecambe report identifies Gladwin as interim head coach and the match as his first home assignment. He made five changes after the Accrington defeat. This establishes active selection responsibility during temporary leadership, rather than a claim about a long-term appointment or a completed rebuilding programme.', s.gladwin),
    section('in-possession', 'MK Dons v Morecambe, 8 March 2025', 'The side used three central defenders, wing-backs and Gilbey and Crowley supporting Orsi. Crosses and combinations both created chances: a Crowley free-kick produced the equaliser, while White and Gilbey helped generate Orsi’s rebound winner. These are observed features of this match, not a permanent stylistic label.', s.gladwin),
    section('management', 'MK Dons at Cheltenham, March 2025', 'Gladwin publicly praised Jack Sanders on his return to the side after an interrupted start at the club. Sanders scored from a short-corner move and White’s delivery. The accessible report provides a concrete example of recognising a returning player’s contribution, without establishing a broader rehabilitation or development methodology.', s.gladwinSanders),
  ], ['Morecambe’s club report was opened and its indexed full article read; the League Paper source supplies only its publicly accessible introduction. Broader pressing and long-term development evidence remain limited.']),
  profile(21652, 'Charlie Adam', [
    section('career', 'Burnley, June 2026 retrospective', 'Burnley described Adam as Head of Academy Player Development working alongside U21 manager Andy Farrell. His account distinguished this role from earlier Fleetwood head-coach and Everton set-piece work. The academy responsibility included helping players progress and overseeing loans; it should not be relabelled sole U21 management.', s.adam),
    section('development', 'Burnley academy, 2025/26', 'Adam discussed bringing high-potential U16 players into older training groups and adapting plans for a younger cohort. George Brierley and Kian McMahon-Brown were specific examples. International exposure and readiness for the next level formed part of the assessment, alongside learning to compete and win.', s.adam),
    section('in-possession', 'Everton set-piece experience; interview April 2026', 'In a direct interview Adam put delivery quality before elaborate movement or blocking routines. He described agreeing the ball’s trajectory with taker and target, visualising the target area and repeating execution. This supports a specialist restart methodology; it does not establish his open-play build-up or defensive model.', s.adamSetPlays),
  ], ['The OLBG source is used only for Adam’s football interview, not betting content. Specialist and academy responsibilities are distinct from senior head-coach results; no September employment certification is made.']),
  profile(24211, 'Chris Brunt', [
    section('career', 'West Bromwich Albion, December 2024', 'Brunt stepped into temporary leadership with Damia Abella and Boaz Myhill after Carlos Corberán’s departure. A short turnaround over Christmas made maintaining preparation the immediate task. His account describes responsibility shared with existing colleagues, not a new permanent management structure.', s.brunt),
    section('out-of-possession', 'West Brom v Sheffield United, 29 December 2024', 'Brunt highlighted second-ball work around Kieffer Moore and awareness of runners such as Hamer and O’Hare. He praised a quicker start than at Derby and midfield competitiveness in the draw. These are specific opponent and match observations rather than evidence of one preferred pressing height.', s.bruntResponse),
    section('management', 'West Brom v Sheffield United, December 2024', 'He recognised Diakité’s contribution alongside Molumby despite the error associated with the opposition goal, noting the midfielder had waited for an opportunity. The response separated an individual mistake from the whole performance. It provides a concrete example of publicly supporting a fringe player after selection.', s.bruntResponse),
  ], ['The temporary Christmas spell supports preparation and player-response observations, not a mature independent tactical system or current job claim.']),
  profile(24677, 'Conor Hourihane', [
    section('career', 'Barnsley, December 2024–August 2025', 'Hourihane’s transition moved through player-coach and assistant duties before interim and then permanent first-team leadership in spring 2025. His August interview explains how coaching alongside playing accelerated that progression. The stages matter: earlier comments from assistant work should not be presented as head-coach match evidence.', s.hourihaneHead),
    section('adaptability', 'Early coaching and Barnsley assistant work; December 2024 interview', 'At part-time Stourbridge he learned to redesign sessions when attendance changed. At Barnsley he described football through build-up and pressing problems rather than formation names, recognising when to play through space and when to bypass pressure. These were explicit coaching principles at that stage.', s.hourihane),
    section('development', 'Barnsley and youth coaching; December 2024 interview', 'He built experience with youth groups and took responsibility for set-piece analysis, video work and individual or unit meetings. That supplies evidence of practical teaching responsibilities beyond his playing reputation. His account also emphasised organisation and emotional control when moving from teammate to coach.', s.hourihane),
  ], ['Coaches’ Voice’s December 2024 narrative concerns assistant and earlier coaching work even if surrounding page labels later change. Current role and causal player-improvement claims are not inferred.']),
  profile(26889, 'Charlie Daniels', [
    section('career', 'Watford development coaching, September 2025', 'Daniels’ direct interview places him in his fifth season of development coaching at Watford. He explained how understanding the purpose behind Eddie Howe’s sessions stimulated his own learning and described further licence study. This is evidence about a practising academy coach, not a senior managerial appointment.', s.daniels),
    section('development', 'Watford, September 2025 interview', 'He prioritised the club’s developmental philosophy and individual needs over imposing a personal formation. His overload-and-switch example illustrated designing a problem to create an opportunity for a winger. It was an explanation of session design, not evidence that a senior team regularly used that pattern.', s.daniels),
    section('management', 'Watford, September 2025 interview', 'Daniels emphasised patience with different development timelines instead of comparing a late developer directly with an early achiever. His own learning involved asking why exercises used particular spaces and constraints. The substantive evidence is reflective teaching and individual progression, rather than tactical conclusions drawn from his former playing position.', s.daniels),
  ], ['The provider record lacks a birth date. Name and Watford context support linkage, but its January 2026 senior-role row is not independently established by this September 2025 development-coach interview. Only one substantive source is used.']),
  profile(26584, 'Christian Fuchs', [
    section('career', 'Newport County appointment, 20 November 2025', 'Newport announced Fuchs after his assistant work with Dean Smith at Charlotte. The announcement establishes a move into the manager’s role in November. His Premier League title as a player supplies biographical context only; it is not a coaching achievement or proof of a preferred style.', s.fuchs),
    section('development', 'Newport County, spring 2026', 'James Crole described the step into full-time football as demanding greater intensity. Conversations with Fuchs clarified what he needed to improve while outside the starting team. Crole associated subsequent progress with increased running output and feedback, providing player testimony about a specific developmental demand.', s.fuchsPlayer),
    section('management', 'Newport County before Crawley, April 2026', 'Crole’s account combines direct standards with encouragement once his contribution improved. The forward discussed a recent goal and assists, while stressing a return to basic competitive work in the survival fight. This supports a contextual example of communication; it does not independently attribute the player’s outputs to coaching.', s.fuchsPlayer),
  ], ['Provider birth date is missing; club and name support linkage. Official appointment is 20 November 2025, conflicting with the provider’s August row. Detailed build-up and pressing structures are not verified by these sources.']),
  profile(28080, 'Colin Calderwood', [
    section('career', 'Northampton Town, March 2026', 'Northampton’s chairman identified Calderwood as technical director overseeing first-team matters for the final seven games while a permanent appointment was deferred. The brief was to collect points during a difficult run. This is explicit interim responsibility within an existing club role, not evidence of permanent managerial tenure.', s.calderwood),
    section('development', 'Northampton Town, May 2026', 'Before Plymouth, Calderwood wanted an academy player on the bench but insisted the opportunity had to be earned. He described the academy as important to the club’s future. The evidence is a stated selection principle, not confirmation of an appearance or proof of a successful graduate pathway.', s.calderwoodYouth),
    section('management', 'Northampton Town, May 2026', 'He expected selection continuity while allowing for players carrying knocks after a busy week. He also acknowledged uncertainty around retention decisions pending a new manager. That illustrates balancing the final competitive fixture with welfare and organisational transition, rather than prematurely promising players outcomes beyond his remit.', s.calderwoodYouth),
  ], ['Provider birth date is absent. Official March 2026 interim context does not validate an August 2025 managerial start in the cache. No detailed tactical style is inferred from technical-director or caretaker status.']),
  profile(28337, 'Colin Kazim-Richards', [
    section('career', 'Crawley Town, March–May 2026', 'Crawley appointed Kazim-Richards on 24 March for the remaining season after coaching in Arsenal’s youth setup and pursuing qualifications. In May the club made the arrangement permanent with Julian Gray continuing as assistant. The survival outcome belongs to that short joint staff period, not his playing achievements.', s.kazim, s.kazimPermanent),
    section('management', 'Crawley Town review, May 2026', 'The owner credited Kazim-Richards and Gray with calming the dressing room and improving relationships with players and staff after a winless run. This is identifiable club testimony about handling a pressured situation. It remains an employer’s assessment rather than an independent psychological evaluation.', s.kazimPermanent),
    section('adaptability', 'Crawley Town appointment interview, May 2026', 'Kazim-Richards distinguished the seven-game rescue from the next task: building staffing, daily standards and a working environment across a full preparation period. His ambition to dominate described a future direction. The interview does not specify possession patterns or pressing triggers sufficient to classify a proven tactical model.', s.kazimPermanent),
  ], ['The provider has no birth date and its September 2025 Crawley start conflicts with the official 24 March 2026 announcement. Name and club linkage is supported; current employment and an established playing style are not inferred.']),
  profile(12718, 'David Horseman', [
    section('career', 'Bristol Rovers, November–December 2024', 'Horseman covered first-team responsibilities during Matt Taylor’s absence and later discussed the limits of caretaker work. He explicitly separated keeping the team moving from building a personal philosophy. That distinction prevents temporary results being presented as a full implementation of his own long-term coaching model.', s.horsemanCup, s.horseman),
    section('adaptability', 'Bristol Rovers before Exeter, December 2024', 'With very little training time, preparation relied on clips and selected work on build-up, pressing and overloads appropriate to the next opponent. Horseman contrasted the coming problem with Wrexham and Stevenage and considered both tactical and physical reasons for changes. The example shows constrained opponent preparation.', s.horseman),
    section('management', 'Bristol Rovers at Barnsley, November 2024', 'After the goalless cup tie and shoot-out progression, he praised defensive work and players meeting unfamiliar demands. He highlighted Senior’s composure after a lengthy absence and Forde’s contribution in a different role. These are specific responses to returning and redeployed players rather than a general development claim.', s.horsemanCup),
  ], ['Temporary cover and caretaker comments concern distinct moments in late 2024. These sources do not provide enough evidence to project the same tactics onto his Forest Green or academy work.']),
  profile(12930, 'David Hughes', [
    section('career', 'Newport County appointment, May 2025', 'Newport appointed Hughes from Manchester United’s U21 coaching staff. His background included academy leadership at Cardiff and Southampton and managing Wales U17s. These are substantial youth-development responsibilities, but should not be inflated into senior Manchester United management or a prior EFL head-coach record.', s.hughes),
    section('development', 'Newport County first interview, May 2025', 'Hughes wanted clear physical, technical and tactical markers in daily work. He discussed judging experience through the games a player had faced rather than age alone, alongside recruitment for energy and standards. This describes an intended evaluation framework; the interview does not demonstrate later improvement against those markers.', s.hughesInterview),
    section('management', 'Newport County first interview, May 2025', 'He welcomed the move into senior responsibility and stressed complementary staff expertise, including Wayne Hatswell’s knowledge and Lee Kendall’s coaching contribution. The desired environment combined consistency, enjoyment and demanding standards. Those are appointment commitments rather than independent evidence of a settled dressing-room culture.', s.hughesInterview),
  ], ['Official appointment date is 23 May 2025, not the provider’s July start. Detailed senior build-up and pressing are not established; youth credentials alone do not establish them. Current employment is not asserted.']),
  profile(24196, 'David Livermore', [
    section('career', 'Millwall temporary leadership, December 2024', 'Livermore described covering after Neil Harris’s departure while valuing the assistant role and its support for others. Continuity and the link between younger and senior players were central to his explanation. His preference expressed in that interview is historical, not a statement of present availability or ambition.', s.livermore),
    section('out-of-possession', 'Millwall at Coventry, 29 December 2024', 'After an unsuccessful higher press against Norwich, he chose a more conservative approach at Coventry and stressed the importance of leaving with a point. The goalless draw supplies a documented opponent-specific adjustment. It should not be converted into a permanent low-block classification across his assistant career.', s.livermoreMatch),
    section('management', 'Millwall at Coventry, December 2024', 'Livermore made only one late substitution, explaining the balance between tiredness and preserving the team’s rhythm. Earlier he had emphasised experienced players helping younger teammates through the change of leadership. Together these comments show short-term continuity decisions, without claiming they establish a long-term player-development programme.', s.livermoreMatch, s.livermore),
  ], ['The tactical evidence concerns two fixtures during temporary charge. It cannot isolate Livermore’s contribution to teams managed by Harris or certify a September 2026 role.']),
]
