import type { DeepResearchProfile, DeepResearchSection } from './deep-research-types.ts'

// Editorial research interpretation, not API observations or scoring inputs.
// Sources opened on 2026-09-14. Historical periods do not establish current employment.
type Source = DeepResearchProfile['sources'][number]
const source = (url: string, title: string, publisher: string): Source => ({ url, title, publisher })
const s = {
  klopp: source('https://learning.coachesvoice.com/cv/jurgen-klopp-tactics-liverpool/', 'The evolution of Jürgen Klopp’s tactics at Liverpool', 'Coaches’ Voice'),
  kloppYouth: source('https://www.liverpoolfc.com/news/how-unique-wembley-experience-can-inspire-liverpools-academy-fa-youth-cup-and-beyond', 'How unique Wembley experience can inspire Liverpool’s Academy in FA Youth Cup and beyond', 'Liverpool FC'),
  nunoAttack: source('https://www.premierleague.com/en/news/3840390', 'How Nuno has helped Forest break loose', 'Premier League'),
  nunoDefence: source('https://www.premierleague.com/en/news/4146784', 'Analysis: Nuno has given Forest the necessary steel', 'Premier League'),
  bruceShape: source('https://www.premierleague.com/en/news/1658845', 'Season trends: Back threes on the rise', 'Premier League'),
  bruceAttack: source('https://www.premierleague.com/en/news/2062021', 'Willock can be Newcastle’s driving force against Villa', 'Premier League'),
  bruceWillock: source('https://www.premierleague.com/en/news/2214353', 'Midfielder Willock seals permanent move to Newcastle', 'Premier League'),
  lampard: source('https://learning.coachesvoice.com/cv/frank-lampard-chelsea-derby-coach/', 'Frank Lampard: Coach Watch', 'Coaches’ Voice'),
  lampardYouth: source('https://www.chelseafc.com/en/news/article/lampard-explains-his-team-s-identity--discusses-mount-s-fitness-', 'Lampard explains his team’s identity, discusses Mount’s fitness, and expresses pride at Academy graduates', 'Chelsea FC'),
  mowbrayCareer: source('https://www.wba.co.uk/news/tony-mowbray-appointed-albion-head-coach', 'Tony Mowbray appointed Albion Head Coach', 'West Bromwich Albion'),
  mowbrayAttack: source('https://www.wba.co.uk/news/tony-mowbray-lets-make-saturday-big-day-us', 'Tony Mowbray: Let’s make Saturday a big day for us', 'West Bromwich Albion'),
  mowbrayAdapt: source('https://www.wba.co.uk/news/tony-mowbray-we-must-be-resolute-search-positive-plymouth-result', 'Tony Mowbray: We must be resolute in search for positive Plymouth result', 'West Bromwich Albion'),
  harris: source('https://www.skysports.com/football/news/11735/11336287/millwall-boss-neil-harris-tells-sky-sports-why-football-clubs-must-reflect-their-fanbase', 'Millwall boss Neil Harris tells Sky Sports why football clubs must reflect their fanbase', 'Sky Sports'),
  harrisCambridge: source('https://www.cambridgeunited.com/news/neil-harris-manager-season-efl-awards', 'Neil Harris up for Manager of the Season at EFL Awards', 'Cambridge United'),
  neilCareer: source('https://learning.coachesvoice.com/cv/alex-neil-interview-norwich-city-hamilton/', 'Used To Winning', 'Coaches’ Voice'),
  neilPreston: source('https://learning.coachesvoice.com/cv/alex-neil-interview-preston-north-end/', 'An Emotional Attachment', 'Coaches’ Voice'),
  warburton: source('https://www.fourfourtwo.com/features/mark-warburton-id-rather-coach-kids-close-ps1-billion-deal-city', 'Mark Warburton: I’d rather coach kids than close a £1 billion deal in the city', 'FourFourTwo'),
  warburtonStaff: source('https://www.brentfordfc.com/en/news/article/mark-looking-to-develop-coaching-pathway_62569', 'Mark looking to develop coaching pathway', 'Brentford FC'),
  warburtonQpr: source('https://academy.coachesvoice.com/programs/mark-warburton-tactics-masterclass-qpr', 'Mark Warburton: Queens Park Rangers 1 Blackburn 0', 'Coaches’ Voice Academy'),
  monk: source('https://learning.coachesvoice.com/cv/garry-monk-swansea-city-arsenal/', 'Garry Monk: Arsenal 0 Swansea City 1', 'Coaches’ Voice'),
  monkPlayer: source('https://www.swanseacity.com/news/top-tactics-have-worked-wonders-says-jazz', 'Top tactics have worked wonders, says Jazz', 'Swansea City'),
  ange: source('https://learning.coachesvoice.com/cv/ange-postecoglou-tactics-tottenham/', 'Ange Postecoglou’s tactics at Tottenham', 'Coaches’ Voice'),
  angeFinal: source('https://www.uefa.com/uefaeuropaleague/news/0299-1dd3728fe683-508b37e6cc11-1000--uefa-europa-league-final-tactical-analysis-spurs-show-nerve/', 'UEFA Europa League final tactical analysis: Spurs show nerves of steel in Bilbao', 'UEFA'),
  warne: source('https://www.dcfc.co.uk/news/2022/10/post-match-verdict-paul-warne-vs-cambridge-united-a', 'Post-Match Verdict: Paul Warne Vs Cambridge United (A)', 'Derby County'),
  warneChampionship: source('https://www.dcfc.co.uk/news/2024/08/staff-interview-everything-is-intensified-warne', 'Pre-match interview: Everything is intensified — Warne', 'Derby County'),
  robins: source('https://learning.coachesvoice.com/mark-robins-coventry-city-league-one-championship/', 'The seeds of recovery', 'Coaches’ Voice'),
  robinsManagement: source('https://www.skysports.com/football/news/11095/12768034/mark-robins-interview-manager-of-the-month-curses-takeover-hopes-and-coventry-s-bright-future', 'Mark Robins interview: Manager of the Month curses, takeover hopes and Coventry’s bright future', 'Sky Sports'),
}

const titles: Record<DeepResearchSection['key'], string> = {
  career: 'Career context', 'in-possession': 'In possession', 'out-of-possession': 'Out of possession',
  adaptability: 'Adaptability', development: 'Player development', management: 'Player management',
}
function section(key: DeepResearchSection['key'], period: string, text: string, ...sources: Source[]): DeepResearchSection {
  return { key, title: titles[key], points: [{ text, period, sourceUrls: sources.map(item => item.url) }] }
}
function profile(apiId: number, name: string, sections: DeepResearchSection[], limitations: string[]): DeepResearchProfile {
  const urls = new Set(sections.flatMap(item => item.points.flatMap(point => point.sourceUrls)))
  return { apiId, name, reviewedAt: '2026-09-14', sections, sources: Object.values(s).filter(item => urls.has(item.url)), limitations }
}

export const DEEP_ADDITIONAL_BRITAIN_PROFILES: DeepResearchProfile[] = [
  profile(1, 'Jürgen Klopp', [
    section('career', 'Liverpool, 2015–February 2024 retrospective', 'Klopp’s Liverpool project combined tactical evolution with the club’s first league title in thirty years. The retrospective charts a move from an initial 4-2-3-1 towards 4-3-3, rather than one unchanged system throughout his tenure.', s.klopp),
    section('in-possession', 'Liverpool, 2016–2018', 'Firmino dropping towards midfield connected possession with Salah and Mané attacking beyond him. High possession did not remove the importance of transitions: the front three offered complementary receiving and penetrating movements, rather than three interchangeable attackers.', s.klopp),
    section('out-of-possession', 'Liverpool, early Klopp seasons from 2015', 'Counterpressing created attacks while opponents were opening out after regaining possession. Midfield support and Firmino pressing back towards the ball helped close escape routes; this also protected Liverpool against counters, linking attacking ambition to collective recovery work.', s.klopp),
    section('development', 'Liverpool, February 2024 League Cup final', 'Clark, Danns, McConnell and Quansah appeared from the bench in the winning final. Academy coach Marc Bridge-Wilkinson described the belief this gave younger players in their route to senior football. This evidences meaningful first-team opportunity under pressure, with credit shared across the academy and senior staff.', s.kloppYouth),
  ], ['The tactical account ends in February 2024; it does not establish a 2026 role. A cup-final opportunity is not a longitudinal development measure.']),

  profile(16, 'Nuno Espírito Santo', [
    section('career', 'Nottingham Forest, December 2023–October 2024 samples', 'The league’s two analyses capture different stages of Forest’s development: immediate attacking changes after Nuno’s arrival, then greater defensive stability in the opening seven league games of 2024/25. They should be read as bounded snapshots.', s.nunoAttack, s.nunoDefence),
    section('in-possession', 'Nottingham Forest at Newcastle, 26 December 2023', 'Wood supplied a central reference point, Gibbs-White connected play behind him, and Elanga and Hudson-Odoi offered wide speed. Leaving attacking outlets upfield helped Forest escape Newcastle’s press. Elanga carrying the ball and Wood running behind showed that direct progression included both dribbling and passing.', s.nunoAttack),
    section('out-of-possession', 'Nottingham Forest, first seven league matches of 2024/25', 'A more settled defensive unit replaced the previous season’s frequent changes. Milenković added aerial strength alongside Murillo, including protection at set plays. Forest could concede possession and retain a clear counterattacking threat, making defensive continuity central to the approach.', s.nunoDefence),
    section('management', 'Nottingham Forest, through October 2024', 'Nuno retained Sels despite earlier mistakes. The league analysis links a settled group and fewer risky short passes with improved assurance. The management interpretation is trust supported by clearer tasks, rather than confidence treated as a personality trait.', s.nunoDefence),
  ], ['Early-season defensive progress does not prove a full-season trend. These Forest examples do not establish subsequent employment or a universal tactical model.']),

  profile(17, 'Steve Bruce', [
    section('career', 'Newcastle United, March 2021', 'This sample comes from a difficult survival campaign: Newcastle were one point above the relegation places with eleven matches remaining, while Wilson, Saint-Maximin and Almirón were absent. Attacking choices therefore need to be assessed against reduced personnel, rather than presented as unconstrained preferences.', s.bruceAttack),
    section('out-of-possession', 'Newcastle United, 2019/20 through April 2020', 'Bruce retained the inherited 5-4-1 as an important structure. The league’s formation review also records 3-5-2 and 3-4-2-1 variants. That supports continuity with several arrangements around three centre-backs; starting shapes alone do not establish pressing triggers or defensive-line height.', s.bruceShape),
    section('in-possession', 'Newcastle United, February–March 2021', 'Willock added movement from central midfield or number ten: carrying forward and arriving late in the box. His debut goal against Southampton followed a surge to meet Saint-Maximin’s service. The useful distinction is an extra runner from deeper positions, not simply another fixed forward.', s.bruceAttack),
    section('development', 'Newcastle United, 2021 loan and August transfer', 'Willock’s loan produced eight goals in fourteen league appearances and a May Player of the Month award before a permanent move. This is a concrete example of a young player gaining productive responsibility in Bruce’s side, without attributing all improvement to the head coach.', s.bruceWillock),
  ], ['Evidence concentrates on Newcastle, not Bruce’s complete career. It does not verify current employment, training methodology or sustained youth-development outcomes.']),

  profile(20, 'Frank Lampard', [
    section('career', 'Chelsea, 2019/20', 'Lampard’s first Chelsea season delivered a top-four finish despite the transfer ban. That context matters when assessing academy opportunities, while the following season’s different attacking personnel made simple continuity more difficult.', s.lampard),
    section('in-possession', 'Chelsea, 2020/21 before January departure', 'Full-backs advanced outside wingers moving infield, with Ziyech and James offering a clearer right-sided combination. Forward runs from midfield suited Mount, but could crowd the areas Werner wanted to attack. The analysis identifies a specific spacing problem rather than a general lack of attacking intent.', s.lampard),
    section('out-of-possession', 'Chelsea, 2019/20', 'Chelsea pressed high, with central midfielders covering inside channels behind advancing full-backs. The demands combined winning the ball nearer goal with protecting the spaces vacated during attacks; the balance depended on coordinated movement across units.', s.lampard),
    section('development', 'Chelsea, 2019–January 2021', 'Lampard described deliberately testing academy graduates against senior competition, citing Mount, Abraham, Tomori and James. Eight graduates had debuted by this interview. Mount’s continued selection reflected work rate and performances, while Lampard also acknowledged the need to balance his minutes with recovery.', s.lampardYouth),
  ], ['The tactical evidence covers the first Chelsea spell, not later Everton or Coventry work. Academy opportunity and measured long-term improvement are different claims.']),

  profile(88, 'Tony Mowbray', [
    section('career', 'West Bromwich Albion, 2007/08 and January 2025 return', 'Albion’s appointment announcement verifies Mowbray’s 2007/08 Championship title and return with longstanding assistant Mark Venus. Its praise of player improvement is the hiring club’s assessment, rather than an independently measured development effect.', s.mowbrayCareer),
    section('in-possession', 'West Bromwich Albion, 24 January 2025', 'Mowbray challenged possession without penetration after the Middlesbrough match. He wanted the ball moved into threatening final-third areas and players uninvolved in build-up arriving in the box. His stated emphasis was converting territorial spells into shots and goals, rather than retaining the ball across the pitch.', s.mowbrayAttack),
    section('adaptability', 'West Bromwich Albion, Plymouth preparation, 30 January 2025', 'Against anticipated aggressive pressure, he described options to progress centrally, around opponents or over them. That is evidence of several permitted routes within an attacking approach, not a commitment to short build-up regardless of the opposition.', s.mowbrayAdapt),
    section('management', 'West Bromwich Albion, 30 January 2025', 'Discussing Bartley’s return, Mowbray resisted rushing an important defender back after limited training. Rejoining the squad environment and rebuilding readiness were separate from immediate selection. The example shows a specific reintegration decision rather than a broad medical or personality judgment.', s.mowbrayAdapt),
  ], ['January interviews describe intentions during an early spell, not season-long execution. They do not establish September 2026 employment or detailed pressing mechanisms.']),

  profile(92, 'Neil Harris', [
    section('career', 'Millwall, 2015–April 2018', 'Harris took his first senior management job in 2015 and led Millwall to League One promotion in 2017. The following April’s interview concerned a Championship play-off challenge still in progress, not a completed promotion or qualification.', s.harris),
    section('in-possession', 'Millwall, 2017/18 through April', 'A direct, aggressive approach used Gregory and Morison as the forward partnership, with Wallace and Marshall providing creativity from wide areas. This combined a recognisable focal point with service and invention around it; physical identity did not mean attacking without creative players.', s.harris),
    section('management', 'Millwall, April 2018 interview', 'Harris linked recruitment to character as well as ability and wanted the team to reflect its supporters. Regular team meals supported relationships, alongside clear discipline and expectations. His account emphasised respect and example in leadership, rather than relying only on confrontation.', s.harris),
    section('out-of-possession', 'Cambridge United, 2025/26 through 8 April 2026', 'Cambridge’s award nomination credited Harris’s side with the EFL’s best defensive record at that date and a fourteen-match unbeaten sequence. This supplies a later defensive outcome, but the announcement does not explain the shape or pressing mechanism responsible.', s.harrisCambridge),
  ], ['The Cambridge source announces a nomination, not an award win or final promotion. Historical Millwall tactics are not automatically Cambridge tactics or current employment evidence.']),

  profile(93, 'Alex Neil', [
    section('career', 'Hamilton and Norwich, 2013–2015; retrospective November 2021', 'Neil’s route combined playing leadership with youth coaching before senior management at Hamilton. Promotion in Scotland preceded his Norwich appointment. He recalled finding a talented Norwich squad needing renewed focus and intensity, making standards as important as recruitment in that initial intervention.', s.neilCareer),
    section('in-possession', 'Preston North End, 2017/18', 'After assessing Preston’s players, Neil sought the aggressive, quick ball movement he associated with his Hamilton and Norwich teams. This was his own account of an intended attacking approach; it does not establish a particular build-up shape or pressing statistic.', s.neilPreston),
    section('adaptability', 'Preston North End, early 2018/19', 'A more expansive approach involving Robinson, Harrop and Nmecha coincided with excessive goals conceded. Neil acknowledged the experiment had failed and returned to the previous season’s approach and experienced core. The example documents correction after a poor start, rather than claiming every change succeeded.', s.neilPreston),
    section('management', 'Preston North End, 2017–2021 retrospective', 'Neil distinguished poor performances from ignoring an opponent-specific plan: the latter frustrated him more. He also recognised that his attachment to a squad gradually broken up by transfers could hinder judgment. This is unusually explicit self-assessment of a relationship-based management trade-off.', s.neilPreston),
  ], ['Neil’s retrospective supplies intentions and reflections, not independent causal proof. Later clubs and September 2026 employment are outside these samples.']),

  profile(97, 'Mark Warburton', [
    section('career', 'Watford to Brentford, through 2013/14', 'Warburton progressed through academy work and a sporting-director role before becoming Brentford manager. His account links that route to observing other European academies and assessing the transition from youth football into senior competition, rather than treating management as an isolated first-team role.', s.warburton),
    section('development', 'Academy work and NextGen, retrospective during Brentford spell', 'He helped create the NextGen under-19 tournament to address insufficient challenge between academy football and first-team selection. This is evidence of designing competitive development opportunities; it does not by itself measure individual players’ improvement or subsequent careers.', s.warburton),
    section('in-possession', 'Queens Park Rangers v Blackburn, October 2021', 'The public masterclass description identifies a plan to free Chair and Willock against Blackburn’s organised, physical defence. That supports a specific focus on creating room for QPR’s creative players. The accessible description does not disclose the full movements used to achieve it.', s.warburtonQpr),
    section('management', 'Brentford, 2013/14 end-of-season interview', 'Warburton described a calm coaching group with complementary expertise. David Weir contributed beyond defensive coaching, while Simon Royce’s work was credited in goalkeeper performances and development. The account makes delegation and communicating knowledge on the training pitch concrete parts of the staff model.', s.warburtonStaff),
  ], ['The QPR evidence is a public video synopsis, not a reviewed full masterclass. No detailed defensive mechanism or current-role claim is inferred.']),

  profile(110, 'Garry Monk', [
    section('career', 'Swansea City, 2014/15', 'Monk’s first full Swansea season included league doubles over Arsenal and Manchester United. Those outcomes provide context for the tactical experiments described by Monk and Jazz Richards; they do not establish that every variation was successful across later jobs.', s.monk),
    section('in-possession', 'Swansea City at Arsenal, 11 May 2015', 'Swansea began without a recognised striker, using Sigurðsson at the front of a 4-3-3. Gomis later came off the bench to score the winner. This is a concrete example of changing the attacking reference point within a match.', s.monk),
    section('adaptability', 'Swansea City, 2014/15 through 13 May', 'Richards described a midfield diamond as an additional option alongside the Arsenal plan. He linked the alternatives to adapting to different situations. His account also notes that Gomis was not ready to start after injury, so the strikerless selection had a personnel constraint as well as tactical intent.', s.monkPlayer),
    section('management', 'Swansea City at Arsenal, May 2015', 'Richards entered unexpectedly for Rangel and credited Monk with making his task clear. He had maintained match fitness on loan at Fulham. The evidence concerns preparation for a specific substitute role, with the loan and senior coaching staff contributing different parts of readiness.', s.monkPlayer),
  ], ['A single Arsenal match cannot establish Monk’s usual pressing intensity. Evidence here does not cover subsequent clubs or current employment.']),

  profile(548, 'Ange Postecoglou', [
    section('career', 'Tottenham Hotspur, May 2025', 'Postecoglou’s Tottenham won the Europa League final against Manchester United. UEFA’s technical review attributes the narrow victory to effective wide delivery and resilient defending, providing a trophy outcome tied to a particular game plan.', s.angeFinal),
    section('in-possession', 'Tottenham Hotspur, first twelve league games of 2023/24', 'The goalkeeper, centre-backs and deepest midfielder formed a build-up diamond. Full-backs moved inside to add central options and draw opponents away from the wingers. Maddison could drop to help progression, then reconnect higher with Son’s runs behind the defence.', s.ange),
    section('out-of-possession', 'Tottenham Hotspur, August–November 2023', 'Son directed the initial press towards one side, with the nearest winger narrowing and then pressing outward to trap play by the touchline. A high defensive line compressed the space for midfield regains and counterpressing, demanding coordinated movement behind the first pressure.', s.ange),
    section('adaptability', 'Europa League final, 21 May 2025', 'Tottenham defended increasingly deep after taking the lead. Danso joined Romero and Van de Ven in a back three late on. UEFA records Postecoglou distinguishing knockout football from league play: this match supports situational adjustment, without erasing the risks of the earlier high-line approach.', s.angeFinal),
  ], ['Early 2023/24 tactics and one 2025 final are different samples. Neither establishes a 2026 role or consistency across whole seasons.']),

  profile(580, 'Paul Warne', [
    section('career', 'Derby County, October 2022–August 2024', 'Warne’s first Derby match was a 2-0 win at Cambridge. By the August 2024 interview, the task had changed to preparing a promoted squad for Championship football. These are distinct stages of the project, not one continuous performance sample.', s.warne, s.warneChampionship),
    section('in-possession', 'Derby County at Cambridge, 1 October 2022', 'Warne described crossing and supplying the box as important to his forwards, but also praised playing behind opponents when short passing was unsuitable. Collins forcing an error illustrated the value of pursuing an apparently unlikely ball rather than waiting for ideal service.', s.warne),
    section('out-of-possession', 'Derby County at Cambridge, 1 October 2022', 'He praised pressure involving the front two, midfield three and wing-backs, intended to deny Cambridge time. Running remained a selection requirement even when tired. He also credited the inherited coaching work, limiting how much of this immediate performance he claimed as his own.', s.warne),
    section('adaptability', 'Derby County, Championship preparation, August 2024', 'Warne expected higher athletic and technical demands, stronger opposition benches and greater punishment for mistakes. He described trying several systems in pre-season and balancing fitness work against injury risk. This records preparation for a changed competitive level, not proof of its eventual effectiveness.', s.warneChampionship),
  ], ['The Cambridge match is one early example. The August interview describes preparation, not a completed Championship assessment or September 2026 employment.']),

  profile(605, 'Mark Robins', [
    section('career', 'Coventry City, 2017–2020', 'Robins returned with Coventry thirteen points from safety and eleven games left. The EFL Trophy win did not prevent relegation, but League Two play-off promotion followed in 2018 and promotion to the Championship in 2020. The sequence distinguishes rebuilding success from immediate survival.', s.robins),
    section('development', 'Coventry City, 2017–2020 retrospective', 'Departures including McNulty, Chaplin and Bayliss made replacement planning essential. Robins credited recruitment staff with identifying young players and preparing alternatives before key exits, alongside opportunities for academy players. The development story includes selling-club constraints and institutional work, rather than attributing every gain to the manager.', s.robins),
    section('management', 'Coventry City, December 2022 interview', 'Amid stadium and ownership uncertainty, Robins emphasised the physical and mental condition of players and staff: areas he could influence directly. He framed progress as a collective effort and stressed that retaining players and adding depth still depended on resources.', s.robinsManagement),
    section('adaptability', 'Coventry City, 2019/20 ground relocation', 'When home games moved to Birmingham, Robins sought to normalise the new venue for players rather than let the disruption define the season. His account connects that response with belief and acceptance of the team’s ideas. It is organisational adaptation, not evidence for an unverified formation change.', s.robins),
  ], ['These interviews support rebuilding, recruitment and management. Detailed possession and pressing mechanisms remain a research gap; historical Coventry roles do not establish current employment.']),
]
